#!/usr/bin/env python3
"""
Database Backup Script
Creates a complete SQL dump of the PostgreSQL database
"""

import os
import sys
from datetime import datetime

try:
    import psycopg2
except ImportError:
    print("Error: psycopg2 not installed")
    sys.exit(1)


def create_database_backup():
    """Create a complete backup of the PostgreSQL database"""
    
    # Get database credentials from environment
    db_config = {
        'host': os.environ.get('PGHOST'),
        'port': os.environ.get('PGPORT'),
        'database': os.environ.get('PGDATABASE'),
        'user': os.environ.get('PGUSER'),
        'password': os.environ.get('PGPASSWORD')
    }
    
    # Validate credentials
    if not all(db_config.values()):
        print("Error: Missing database credentials")
        sys.exit(1)
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    backup_file = f'backups/database_full_backup_{timestamp}.sql'
    
    print(f"Creating database backup: {backup_file}")
    print(f"Database: {db_config['database']}")
    
    try:
        # Connect to database
        conn = psycopg2.connect(**db_config)
        cursor = conn.cursor()
        
        # Open backup file
        with open(backup_file, 'w') as f:
            # Write header
            f.write(f"-- PostgreSQL Database Backup\n")
            f.write(f"-- Database: {db_config['database']}\n")
            f.write(f"-- Date: {datetime.now().isoformat()}\n")
            f.write(f"-- Generated by AI Multi-Agent System\n\n")
            
            # Get all tables
            cursor.execute("""
                SELECT tablename 
                FROM pg_tables 
                WHERE schemaname = 'public'
                ORDER BY tablename;
            """)
            
            tables = cursor.fetchall()
            
            if not tables:
                f.write("-- No tables found in database\n")
                print("Warning: No tables found in database")
            else:
                print(f"Found {len(tables)} table(s) to backup")
                
                for (table_name,) in tables:
                    print(f"  - Backing up table: {table_name}")
                    
                    # Get table schema
                    cursor.execute(f"""
                        SELECT column_name, data_type, character_maximum_length
                        FROM information_schema.columns
                        WHERE table_name = %s
                        ORDER BY ordinal_position;
                    """, (table_name,))
                    
                    columns = cursor.fetchall()
                    
                    # Write table header
                    f.write(f"\n-- Table: {table_name}\n")
                    f.write(f"-- Columns: {len(columns)}\n")
                    
                    # Get CREATE TABLE statement
                    try:
                        cursor.execute(f"""
                            SELECT 'CREATE TABLE ' || quote_ident(tablename) || ' (' ||
                                   string_agg(quote_ident(attname) || ' ' || 
                                   format_type(atttypid, atttypmod), ', ') || ');'
                            FROM pg_attribute
                            JOIN pg_class ON pg_class.oid = pg_attribute.attrelid
                            JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
                            WHERE pg_class.relname = %s
                              AND pg_attribute.attnum > 0
                              AND NOT pg_attribute.attisdropped
                            GROUP BY tablename;
                        """, (table_name,))
                        
                        create_stmt = cursor.fetchone()
                        if create_stmt:
                            f.write(f"DROP TABLE IF EXISTS {table_name} CASCADE;\n")
                            f.write(f"{create_stmt[0]}\n\n")
                    except:
                        # Fallback to simple column info
                        col_defs = []
                        for col_name, data_type, max_length in columns:
                            if max_length:
                                col_defs.append(f"{col_name} {data_type}({max_length})")
                            else:
                                col_defs.append(f"{col_name} {data_type}")
                        
                        f.write(f"DROP TABLE IF EXISTS {table_name} CASCADE;\n")
                        f.write(f"CREATE TABLE {table_name} ({', '.join(col_defs)});\n\n")
                    
                    # Get table data
                    cursor.execute(f"SELECT * FROM {table_name};")
                    rows = cursor.fetchall()
                    
                    if rows:
                        f.write(f"-- Data for table: {table_name} ({len(rows)} rows)\n")
                        
                        col_names = [desc[0] for desc in cursor.description]
                        
                        for row in rows:
                            values = []
                            for val in row:
                                if val is None:
                                    values.append('NULL')
                                elif isinstance(val, str):
                                    # Escape single quotes
                                    escaped = val.replace("'", "''")
                                    values.append(f"'{escaped}'")
                                elif isinstance(val, (int, float)):
                                    values.append(str(val))
                                else:
                                    values.append(f"'{str(val)}'")
                            
                            f.write(f"INSERT INTO {table_name} ({', '.join(col_names)}) VALUES ({', '.join(values)});\n")
                        
                        f.write("\n")
                    else:
                        f.write(f"-- No data in table: {table_name}\n\n")
            
            # Write footer
            f.write(f"\n-- Backup completed: {datetime.now().isoformat()}\n")
        
        cursor.close()
        conn.close()
        
        # Get file size
        file_size = os.path.getsize(backup_file)
        print(f"\n✓ Backup created successfully!")
        print(f"  File: {backup_file}")
        print(f"  Size: {file_size} bytes ({file_size/1024:.2f} KB)")
        
        return backup_file
        
    except Exception as e:
        print(f"Error creating backup: {e}")
        sys.exit(1)


if __name__ == "__main__":
    create_database_backup()
